language: php 
php: 
 - 5.6

sudo: false

notifications:
  email:
    secure: TNv7WYCJ1ei3wgoXtNM+/Je4ZU7fgcUSsAUQnjC8h2MIE0ImwxPC2xt5t6BR8Mi6XrPCBQ1aRjAvhSFGdYcfhWDJwU0Nq6BfynVwE4OR5/KNhZ9TvMlCQ+eRQD8qJLNqe2MWxMZcdlbrk0rNEhTDcPn3b6dz9Zuji4woe5wksxA=

env:
 - DB=MYSQL CORE_RELEASE=3.6
 - DB=PGSQL CORE_RELEASE=3.6
 - DB=SQLITE3 CORE_RELEASE=3.6

before_script:
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss
 - php translatablerouting/tests/pre-up/travis_setup.php --target ~/builds/ss

script: 
 - phpunit translatablerouting/tests/
